name: Conditional Workflow

on: push

permissions:
  actions: write

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.set-value.outputs.value }}
    steps:
      - name: Set Value
        id: set-value
        run: echo "::set-output name=value::9"  

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: needs.job1.outputs.value > 10
    steps:
      - name: Run if value is greater than 10
        run: echo "Value is greater than 10"

  cleanup:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ needs.job1.outputs.value }} <= 10
    steps:
      - name: Delete Workflow Run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          run_id=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=1" \
            | jq -r '.workflow_runs[0].id')
          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
