name: Conditional Workflow

on: push 

permissions: write-all 
#  actions: write

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.set-value.outputs.value }}
    steps:
      - name: Set Value
        id: set-value
        run: echo "::set-output name=value::9"  

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: needs.job1.outputs.value > 10
    steps:
      - name: Run if value is greater than 10
        run: echo "Value is greater than 10"

  yaml

name: Your Workflow

jobs:
  first-job:
    runs-on: ubuntu-latest
    outputs:
      should_run_second: ${{ steps.check.outputs.should_run }} # Example output
    steps:
      - id: check
        run: |
          # Your logic to determine if second job should run
          echo "should_run=true" >> $GITHUB_OUTPUT # or false

  second-job:
    needs: first-job
    if: needs.first-job.outputs.should_run_second == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Your second job steps
        run: echo "Running second job"

  cleanup-job:
    needs: second-job
    if: always() && needs.second-job.result == 'skipped'
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow run
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}"

