name: Conditional Workflow

on: push 

permissions: write-all 
#  actions: write

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.set-value.outputs.value }}
    steps:
      - name: Set Value
        id: set-value
        run: echo "::set-output name=value::9"  

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: needs.job1.outputs.value > 10
    steps:
      - name: Run if value is greater than 10
        run: echo "Value is greater than 10"

  cleanup-job:
    needs: job1
    if: always() && needs.job1.outputs.value <= 10
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/13661476913"
# ${{ github.run_id }}

